# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [1]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [2]:
# your code here
np.__version__

'1.16.5'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [24]:
# Method 1
a=np.random.random((2,3,5))

In [ ]:
# Method 2


In [ ]:
# Method 3

#### 4. Print *a*.


In [25]:
# your code here
a

array([[[0.10857175, 0.51111143, 0.12827975, 0.94410211, 0.52526343],
        [0.51640378, 0.04160048, 0.36789798, 0.53866241, 0.14598872],
        [0.71853323, 0.73983273, 0.6731079 , 0.31852601, 0.38151643]],

       [[0.88371213, 0.78086914, 0.17961859, 0.52226632, 0.66323432],
        [0.65917675, 0.17037411, 0.59440209, 0.96140854, 0.19367901],
        [0.7301216 , 0.23175578, 0.01785782, 0.31347806, 0.96264299]]])

#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [13]:
# your code here
b=np.zeros((5,2,3))+1

#### 6. Print *b*.


In [14]:
# your code here
b

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [28]:
# your code here
a.shape==b.shape
a.size==b.size

True

#### 8. Are you able to add *a* and *b*? Why or why not?


In [27]:
# your answer here
a+b
#no, they have not same shape

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [45]:
# your code here
#a=2x3x5
#b=5x2x3
#we want 2 in 1st and this is the 2nd(so 1), 3 in secon and this is the third(=2) and 5 in last and this is the 1st (so 0)
c=b.transpose(1,2,0)
c

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [46]:
# your code/answer here
d=a+c
d
#it works because same shape

array([[[1.10857175, 1.51111143, 1.12827975, 1.94410211, 1.52526343],
        [1.51640378, 1.04160048, 1.36789798, 1.53866241, 1.14598872],
        [1.71853323, 1.73983273, 1.6731079 , 1.31852601, 1.38151643]],

       [[1.88371213, 1.78086914, 1.17961859, 1.52226632, 1.66323432],
        [1.65917675, 1.17037411, 1.59440209, 1.96140854, 1.19367901],
        [1.7301216 , 1.23175578, 1.01785782, 1.31347806, 1.96264299]]])

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [47]:
# your code/answer here
print (a, d)
#l'une est l'autre +1

[[[0.10857175 0.51111143 0.12827975 0.94410211 0.52526343]
  [0.51640378 0.04160048 0.36789798 0.53866241 0.14598872]
  [0.71853323 0.73983273 0.6731079  0.31852601 0.38151643]]

 [[0.88371213 0.78086914 0.17961859 0.52226632 0.66323432]
  [0.65917675 0.17037411 0.59440209 0.96140854 0.19367901]
  [0.7301216  0.23175578 0.01785782 0.31347806 0.96264299]]] [[[1.10857175 1.51111143 1.12827975 1.94410211 1.52526343]
  [1.51640378 1.04160048 1.36789798 1.53866241 1.14598872]
  [1.71853323 1.73983273 1.6731079  1.31852601 1.38151643]]

 [[1.88371213 1.78086914 1.17961859 1.52226632 1.66323432]
  [1.65917675 1.17037411 1.59440209 1.96140854 1.19367901]
  [1.7301216  1.23175578 1.01785782 1.31347806 1.96264299]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [48]:
# your code here
e=a*c
e

array([[[0.10857175, 0.51111143, 0.12827975, 0.94410211, 0.52526343],
        [0.51640378, 0.04160048, 0.36789798, 0.53866241, 0.14598872],
        [0.71853323, 0.73983273, 0.6731079 , 0.31852601, 0.38151643]],

       [[0.88371213, 0.78086914, 0.17961859, 0.52226632, 0.66323432],
        [0.65917675, 0.17037411, 0.59440209, 0.96140854, 0.19367901],
        [0.7301216 , 0.23175578, 0.01785782, 0.31347806, 0.96264299]]])

#### 13. Does *e* equal to *a*? Why or why not?


In [ ]:
# your code/answer here
#because c is a matrice of 1 

#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [77]:
# your code here
d_max=np.max(d)
d_min=np.min(d)
d_mean=np.mean(d)
print(d_max,d_min,d_mean)

1.9626429871940603 1.017857816058976 1.484133179516533


#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [59]:
# your code here
f=np.empty((2,3,5))
f

array([[[1.10857175, 1.51111143, 1.12827975, 1.94410211, 1.52526343],
        [1.51640378, 1.04160048, 1.36789798, 1.53866241, 1.14598872],
        [1.71853323, 1.73983273, 1.6731079 , 1.31852601, 1.38151643]],

       [[1.88371213, 1.78086914, 1.17961859, 1.52226632, 1.66323432],
        [1.65917675, 1.17037411, 1.59440209, 1.96140854, 1.19367901],
        [1.7301216 , 1.23175578, 1.01785782, 1.31347806, 1.96264299]]])

#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [80]:
# your code here
print(d_max,d_min,d_mean)
d
d.shape

1.9626429871940603 1.017857816058976 1.484133179516533


(2, 3, 5)

In [86]:
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if (d[i,j,k]<d_mean) & (d[i,j,k]>d_min):
                f[i,j,k]=25
            elif (d[i,j,k]>d_mean) & (d[i,j,k]<d_max):
                f[i,j,k]=75
            elif d[i,j,k]==d_mean:
                f[i,j,k]=50
            elif d[i,j,k]==d_min:
                 f[i,j,k]=0
            elif d[i,j,k]==d_max:
                 f[i,j,k]=100
print(f)
        

[[[ 25.  75.  25.  75.  75.]
  [ 75.  25.  25.  75.  25.]
  [ 75.  75.  75.  25.  25.]]

 [[ 75.  75.  25.  75.  75.]
  [ 75.  25.  75.  75.  25.]
  [ 75.  25.   0.  25. 100.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [88]:
# your code here
print(d, f)

[[[1.10857175 1.51111143 1.12827975 1.94410211 1.52526343]
  [1.51640378 1.04160048 1.36789798 1.53866241 1.14598872]
  [1.71853323 1.73983273 1.6731079  1.31852601 1.38151643]]

 [[1.88371213 1.78086914 1.17961859 1.52226632 1.66323432]
  [1.65917675 1.17037411 1.59440209 1.96140854 1.19367901]
  [1.7301216  1.23175578 1.01785782 1.31347806 1.96264299]]] [[[ 25.  75.  25.  75.  75.]
  [ 75.  25.  25.  75.  25.]
  [ 75.  75.  75.  25.  25.]]

 [[ 75.  75.  25.  75.  75.]
  [ 75.  25.  75.  75.  25.]
  [ 75.  25.   0.  25. 100.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [90]:
# your code here
for i in range(d.shape[0]):
    for j in range(d.shape[1]):
        for k in range(d.shape[2]):
            if (d[i,j,k]<d_mean) & (d[i,j,k]>d_min):
                f[i,j,k]='B'
            elif (d[i,j,k]>d_mean) & (d[i,j,k]<d_max):
                f[i,j,k]='D'
            elif d[i,j,k]==d_mean:
                f[i,j,k]='C'
            elif d[i,j,k]==d_min:
                 f[i,j,k]='A'
            elif d[i,j,k]==d_max:
                 f[i,j,k]='E'
print(f)

ValueError: could not convert string to float: 'B'